
MODEL_DICT = {
    '$"models/humans/pilots/pilot_medium_geist_m.mdl"': "pilots/grapple_cropped.png",
    '$"models/humans/pilots/pilot_medium_geist_f.mdl"': "pilots/grapple_cropped.png",
    '$"models/titans/medium/titan_medium_ajax.mdl"': "titans/iont.png",
    '$"models/titans/heavy/titan_heavy_ogre.mdl"': "titans/scorcht.png",
    '$"models/titans/light/titan_light_raptor.mdl"': "titans/northstart.png",
    '$"models/titans/light/titan_light_locust.mdl"': "titans/ronint.png",
    '$"models/titans/medium/titan_medium_wraith.mdl"': "titans/tonet.png",
    '$"models/humans/pilots/pilot_heavy_drex_f.mdl"': "pilots/cloak_cropped.png",
    '$"models/humans/pilots/pilot_heavy_drex_m.mdl"': "pilots/cloak_cropped.png",
    '$"models/titans/heavy/titan_heavy_deadbolt.mdl"': "titans/legiont.png",
    '$"models/titans/medium/titan_medium_vanguard.mdl"': "titans/monarcht.png",
    '$"models/titans/medium/titan_medium_ion_prime.mdl"': "titans/iont.png",
    '$"models/titans/heavy/titan_heavy_scorch_prime.mdl"': "titans/scorcht.png",
    '$"models/titans/light/titan_light_northstar_prime.mdl"': "titans/northstart.png",
    '$"models/titans/light/titan_light_ronin_prime.mdl"': "titans/ronint.png",
    '$"models/titans/medium/titan_medium_tone_prime.mdl"': "titans/tonet.png",
    '$"models/titans/heavy/titan_heavy_legion_prime.mdl"': "titans/legiont.png",
    '$"models/humans/pilots/pilot_heavy_roog_m.mdl"': "pilots/a-wall_cropped.png",
    '$"models/humans/pilots/pilot_heavy_roog_f.mdl"': "pilots/a-wall_cropped.png",
    '$"models/humans/pilots/pilot_medium_reaper_m.mdl"': "pilots/pulse_cropped.png",
    '$"models/humans/pilots/pilot_medium_reaper_f.mdl"': "pilots/pulse_cropped.png",
    '$"models/humans/pilots/pilot_light_jester_m.mdl"': "pilots/stim_cropped.png",
    '$"models/humans/pilots/pilot_light_jester_f.mdl"': "pilots/stim_cropped.png",
    '$"models/humans/pilots/pilot_light_ged_m.mdl"': "pilots/phase_cropped.png",
    '$"models/humans/pilots/pilot_light_ged_f.mdl"': "pilots/phase_cropped.png",
    '$"models/humans/pilots/pilot_medium_stalker_m.mdl"': "pilots/holo_cropped.png",
    '$"models/humans/pilots/pilot_medium_stalker_f.mdl"': "pilots/holo_cropped.png",
    "true models/titans/atlas/atlas_titan.mdl": "titanfall1/titans/atlas_militia_cropped.png",
    "false models/titans/atlas/atlas_titan.mdl": "titanfall1/titans/atlas_imc_cropped.png",
    "true models/titans/ogre/ogre_titan.mdl": "titanfall1/titans/ogre_militia_cropped.png",
    "false models/titans/ogre/ogre_titan.mdl": "titanfall1/titans/ogre_imc_cropped.png",
    "true models/titans/stryder/stryder_titan.mdl": "titanfall1/titans/stryder_militia_cropped.png",
    "false models/titans/stryder/stryder_titan.mdl": "titanfall1/titans/stryder_imc_cropped.png",
    "false models/humans/pilot/female_br/pilot_female_br.mdl": "titanfall1/pilots/f_br_imc_cropped.png",
    "true models/humans/pilot/female_br/pilot_female_br.mdl": "titanfall1/pilots/f_br_militia_cropped.png",
    "false models/Humans/imc_pilot/male_br/imc_pilot_male_br.mdl": "titanfall1/pilots/m_br_imc_cropped.png",
    "true models/Humans/mcor_pilot/male_br/mcor_pilot_male_br.mdl": "titanfall1/pilots/m_br_militia_cropped.png",
    "false models/humans/pilot/female_cq/pilot_female_cq.mdl": "titanfall1/pilots/f_cq_imc_cropped.png",
    "true models/humans/pilot/female_cq/pilot_female_cq.mdl": "titanfall1/pilots/f_cq_militia_cropped.png",
    "false models/humans/imc_pilot/male_cq/imc_pilot_male_cq.mdl": "titanfall1/pilots/m_cq_imc_cropped.png",
    "true models/humans/mcor_pilot/male_cq/mcor_pilot_male_cq.mdl": "titanfall1/pilots/m_cq_militia_cropped.png",
    "false models/humans/pilot/female_dm/pilot_female_dm.mdl": "titanfall1/pilots/f_dm_imc_cropped.png",
    "true models/humans/pilot/female_dm/pilot_female_dm.mdl": "titanfall1/pilots/f_dm_militia_cropped.png",
    "false models/humans/imc_pilot/male_dm/imc_pilot_male_dm.mdl": "titanfall1/pilots/m_dm_imc_cropped.png",
    "true models/humans/mcor_pilot/male_dm/mcor_pilot_male_dm.mdl": "titanfall1/pilots/m_dm_militia_cropped.png",
    "unknown": "unknown/unkownpfp.png",
    "confused": "unknown/confused.jpg"
}


WEAPON_NAMES = {
  "mp_weapon_rspn101": "R-201 Carbine",
  "mp_weapon_rspn101_og": "R-101 Carbine",
  "mp_weapon_hemlok": "Hemlock BF-R",
  "mp_weapon_vinson": "V-47 Flatline",
  "mp_weapon_g2": "G2A5",
  "mp_weapon_car": "CAR",
  "mp_weapon_alternator_smg": "Alternator",
  "mp_weapon_hemlok_smg": "Volt",
  "mp_weapon_r97": "R-97",
  "mp_weapon_lmg": "Spitfire",
  "mp_weapon_lstar": "L-STAR",
  "mp_weapon_esaw": "Devotion",
  "mp_weapon_sniper": "Kraber",
  "mp_weapon_doubletake": "Double Take",
  "mp_weapon_dmr": "Longbow DMR",
  "mp_weapon_shotgun": "EVA-8 Auto",
  "mp_weapon_mastiff": "Mastiff",
  "mp_weapon_smr": "Sidewinder SMR",
  "mp_weapon_epg": "EPG",
  "mp_weapon_softball": "Softball",
  "mp_weapon_pulse_lmg": "EM-4 Cold War",
  "mp_weapon_semipistol": "P2016",
  "mp_weapon_autopistol": "RE-45 Auto",
  "mp_weapon_wingman": "B3 Wingman",
  "mp_weapon_wingman_n": "Wingman Elite",
  "mp_weapon_shotgun_pistol": "Mozambique",
  "mp_weapon_smart_pistol": "Smart Pistol",
  "mp_weapon_defender": "Charge Rifle",
  "mp_weapon_mgl": "MGL",
  "mp_weapon_arc_launcher": "LG-97 Thunderbolt",
  "mp_weapon_rocket_launcher": "Archer",
  "mp_weapon_frag_grenade": "Frag Grenade",
  "mp_weapon_grenade_emp": "Arc Grenade",
  "mp_weapon_thermite_grenade": "Firestar",
  "mp_weapon_grenade_gravity": "Gravity Star",
  "mp_weapon_grenade_electric_smoke": "Electric Smoke",
  "mp_weapon_satchel": "Satchel",
  "mp_ability_cloak": "Cloak",
  "mp_weapon_grenade_sonar": "Pulse Blade",
  "mp_ability_grapple": "Grapple",
  "mp_ability_heal": "Stim",
  "mp_weapon_deployable_cover": "A-Wall",
  "mp_ability_shifter": "Phase Shift",
  "mp_ability_holopilot": "Holopilot",
  "mp_titanability_smoke": "Ability Electric Smoke",
  "mp_titanability_electric_smoke": "Global Electric Smoke",
  "mp_titanability_nuke_eject": "Nuke Ejection",
  "mp_titanweapon_rocketeer_rocketstream": "Quad Rocket",
  "mp_titanweapon_particle_accelerator": "Splitter Rifle",
  "mp_titanweapon_laser_lite": "Laser Shot",
  "mp_titanability_laser_trip": "Tripwire",
  "mp_titanweapon_vortex_shield_ion": "Vortex Shield",
  "mp_titancore_laser_cannon": "Laser Core",
  "mp_titanweapon_meteor": "Thermite Launcher",
  "mp_titanweapon_flame_wall": "Flame Wall",
  "mp_titanability_slow_trap": "Incendiary Trap",
  "mp_titanweapon_heat_shield": "Thermal Shield",
  "mp_titancore_flame_wave": "Flame Core",
  "mp_titanweapon_sniper": "Plasma Railgun",
  "mp_titanweapon_dumbfire_rockets": "Cluster Missile",
  "mp_titanability_hover": "VTOL Hover",
  "mp_titanability_tether_trap": "Tether Trap",
  "mp_titancore_flight_core": "Flight Core",
  "mp_titanweapon_leadwall": "Leadwall",
  "mp_titanweapon_arc_wave": "Arc Wave",
  "mp_titanability_phase_dash": "Phase Dash",
  "mp_titanability_basic_block": "Sword Block",
  "mp_titancore_shift_core": "Sword Core",
  "mp_titanweapon_sticky_40mm": "40MM Tracker cannon",
  "mp_titanweapon_tracker_rockets": "Tracking Rockets",
  "mp_titanability_sonar_pulse": "Sonar Pulse",
  "mp_titanability_particle_wall": "Particle Wall",
  "mp_titancore_salvo_core": "Salvo Core",
  "mp_titanweapon_predator_cannon": "Predator Cannon",
  "mp_titanability_power_shot": "Power Shot",
  "mp_titanability_ammo_swap": "Mode Switch",
  "mp_titanability_gun_shield": "Gun Shield",
  "mp_titancore_siege_mode": "Smart Core",
  "mp_titanweapon_xo16_vanguard": "XO-16",
  "mp_titanweapon_salvo_rockets": "Rocket Salvo",
  "mp_titanweapon_shoulder_rockets": "Multi Target Missiles",
  "mp_titanability_rearm": "Rearm",
  "mp_titanweapon_stun_laser": "Energy Siphon",
  "mp_titancore_upgrade": "Upgrade Core"
}
CSS_COLOURS = {
    "black": (0, 0, 0),
    "silver": (192, 192, 192),
    "gray": (128, 128, 128),
    "white": (255, 255, 255),
    "maroon": (128, 0, 0),
    "red": (255, 0, 0),
    "purple": (128, 0, 128),
    "fuchsia": (255, 0, 255),
    "green": (0, 128, 0),
    "lime": (0, 255, 0),
    "olive": (128, 128, 0),
    "yellow": (255, 255, 0),
    "navy": (0, 0, 128),
    "blue": (0, 0, 255),
    "teal": (0, 128, 128),
    "aqua": (0, 255, 255),
    "aliceblue": (240, 248, 255),
    "antiquewhite": (250, 235, 215),
    "aquamarine": (127, 255, 212),
    "azure": (240, 255, 255),
    "beige": (245, 245, 220),
    "bisque": (255, 228, 196),
    "blanchedalmond": (255, 235, 205),
    "blueviolet": (138, 43, 226),
    "brown": (165, 42, 42),
    "burlywood": (222, 184, 135),
    "cadetblue": (95, 158, 160),
    "chartreuse": (127, 255, 0),
    "chocolate": (210, 105, 30),
    "coral": (255, 127, 80),
    "cornflowerblue": (100, 149, 237),
    "cornsilk": (255, 248, 220),
    "crimson": (220, 20, 60),
    "cyan": (0, 255, 255),
    "darkblue": (0, 0, 139),
    "darkcyan": (0, 139, 139),
    "darkgoldenrod": (184, 134, 11),
    "darkgray": (169, 169, 169),
    "darkgreen": (0, 100, 0),
    "darkkhaki": (189, 183, 107),
    "darkmagenta": (139, 0, 139),
    "darkolivegreen": (85, 107, 47),
    "darkorange": (255, 140, 0),
    "darkorchid": (153, 50, 204),
    "darkred": (139, 0, 0),
    "darksalmon": (233, 150, 122),
    "darkseagreen": (143, 188, 143),
    "darkslateblue": (72, 61, 139),
    "darkslategray": (47, 79, 79),
    "darkturquoise": (0, 206, 209),
    "darkviolet": (148, 0, 211),
    "deeppink": (255, 20, 147),
    "deepskyblue": (0, 191, 255),
    "dimgray": (105, 105, 105),
    "dodgerblue": (30, 144, 255),
    "firebrick": (178, 34, 34),
    "floralwhite": (255, 250, 240),
    "forestgreen": (34, 139, 34),
    "gainsboro": (220, 220, 220),
    "ghostwhite": (248, 248, 255),
    "gold": (255, 215, 0),
    "goldenrod": (218, 165, 32),
    "greenyellow": (173, 255, 47),
    "honeydew": (240, 255, 240),
    "hotpink": (255, 105, 180),
    "indianred": (205, 92, 92),
    "indigo": (75, 0, 130),
    "ivory": (255, 255, 240),
    "khaki": (240, 230, 140),
    "lavender": (230, 230, 250),
    "lavenderblush": (255, 240, 245),
    "lawngreen": (124, 252, 0),
    "lemonchiffon": (255, 250, 205),
    "lightblue": (173, 216, 230),
    "lightcoral": (240, 128, 128),
    "lightcyan": (224, 255, 255),
    "lightgoldenrodyellow": (250, 250, 210),
    "lightgray": (211, 211, 211),
    "lightgreen": (144, 238, 144),
    "lightpink": (255, 182, 193),
    "lightsalmon": (255, 160, 122),
    "lightseagreen": (32, 178, 170),
    "lightskyblue": (135, 206, 235),
    "lightslategray": (119, 136, 153),
    "lightsteelblue": (176, 196, 222),
    "lightyellow": (255, 255, 224),
    "limegreen": (50, 205, 50),
    "linen": (250, 240, 230),
    "mediumaquamarine": (102, 205, 170),
    "mediumblue": (0, 0, 205),
    "mediumorchid": (186, 85, 211),
    "mediumpurple": (147, 112, 219),
    "mediumseagreen": (60, 179, 113),
    "mediumslateblue": (123, 104, 238),
    "mediumspringgreen": (0, 250, 154),
    "mediumturquoise": (72, 209, 204),
    "mediumvioletred": (199, 21, 133),
    "midnightblue": (25, 25, 112),
    "mintcream": (245, 255, 250),
    "mistyrose": (255, 228, 225),
    "moccasin": (255, 228, 181),
    "navajowhite": (255, 222, 173),
    "oldlace": (253, 245, 230),
    "olivedrab": (107, 142, 35),
    "orange": (255, 165, 0),
    "orangered": (255, 69, 0),
    "orchid": (218, 112, 214),
    "palegoldenrod": (238, 232, 170),
    "palegreen": (152, 251, 152),
    "paleturquoise": (175, 238, 238),
    "palevioletred": (219, 112, 147),
    "papayawhip": (255, 239, 213),
    "peachpuff": (255, 218, 185),
    "peru": (205, 133, 63),
    "pink": (255, 192, 203),
    "plum": (221, 160, 221),
    "powderblue": (176, 224, 230),
    "purple": (128, 0, 128),
    "rebeccapurple": (102, 51, 153),
    "red": (255, 0, 0),
    "rosybrown": (188, 143, 143),
    "royalblue": (65, 105, 225),
    "saddlebrown": (139, 69, 19),
    "salmon": (250, 128, 114),
    "sandybrown": (244, 164, 96),
    "seagreen": (46, 139, 87),
    "seashell": (255, 245, 238),
    "sienna": (160, 82, 45),
    "silver": (192, 192, 192),
    "skyblue": (135, 206, 235),
    "slateblue": (106, 90, 205),
    "slategray": (112, 128, 144),
    "snow": (255, 250, 250),
    "springgreen": (0, 255, 127),
    "steelblue": (70, 130, 180),
    "tan": (210, 180, 140),
    "teal": (0, 128, 128),
    "thistle": (216, 191, 216),
    "tomato": (255, 99, 71),
    "turquoise": (64, 224, 208),
    "violet": (238, 130, 238),
    "wheat": (245, 222, 179),
    "white": (255, 255, 255),
    "whitesmoke": (245, 245, 245),
    "yellow": (255, 255, 0),
    "yellowgreen": (154, 205, 50),
    "lblue":(30, 144, 255),
    "lcoral": (240, 128, 128),
    "lcya": (0, 255, 255),
    "lpink": (255, 20, 147),
    "lred": (255, 69, 0),
    "lgreen": (0, 255, 127),
    "lvio" : (238, 130, 238),
    "llblue": (135, 206, 235)
    }

MAP_NAME_TABLE = {
    "mp_angel_city": "Angel City",
    "mp_black_water_canal": "Black Water Canal",
    "mp_coliseum": "Coliseum",
    "mp_coliseum_column": "Pillars",
    "mp_colony02": "Colony",
    "mp_complex3": "Complex",
    "mp_crashsite3": "Crash Site",
    "mp_drydock": "Drydock",
    "mp_eden": "Eden",
    "mp_forwardbase_kodai": "Forwardbase Kodai",
    "mp_glitch": "Glitch",
    "mp_grave": "Boomtown",
    "mp_homestead": "Homestead",
    "mp_lf_deck": "Deck",
    "mp_lf_meadow": "Meadow",
    "mp_lf_stacks": "Stacks",
    "mp_lf_township": "Township",
    "mp_lf_traffic": "Traffic",
    "mp_lf_uma": "UMA",
    "mp_relic02": "Relic",
    "mp_rise": "Rise",
    "mp_thaw": "Exoplanet",
    "mp_wargames": "Wargames",
    "mp_mirror_city": "Mirror City",
    "mp_brick": "BRICK",
}