# Base image
FROM python:3.13-slim

# Set working directory
WORKDIR /app
# COPY ./requirements.txt ./requirements.txt
# Install system dependencies for font rendering
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libfontconfig1-dev \
    fontconfig \
    fonts-dejavu \
    && rm -rf /var/lib/apt/lists/*

# Copy bot code
COPY . .
COPY ./data/commands.json .

# Install dependencies
RUN python -m venv /venv && \
    /venv/bin/pip install --no-cache-dir -r ./requirements.txt

# Set environment variable for virtual environment
ENV PATH="/venv/bin:$PATH"

ENV PYTHONUNBUFFERED=1


# Expose Flask port
EXPOSE 3451

# Command to run the bot
CMD ["python3", "output.py"]
